'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { usePartnerStore } from '@/lib/store';
import { PROFESSION_OPTIONS } from '@/lib/mock-data';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { CustomSelect } from '@/components/ui/CustomSelect';
import {
  UsersThree,
  UserPlus,
  Copy,
  CheckCircle,
  ShareNetwork,
  Lightning,
  Sparkle,
  ShieldCheck,
  Phone,
  Envelope,
  User,
  MapPin,
  Coins,
  ClipboardText,
  Gift,
} from '@phosphor-icons/react';

export default function TeamPage() {
  const router = useRouter();
  const { partner, teamMembers, onboardTeamMember } = usePartnerStore();

  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Onboard Member Form State
  const [memberName, setMemberName] = useState('');
  const [memberEmail, setMemberEmail] = useState('');
  const [memberPhone, setMemberPhone] = useState('');
  const [memberProfession, setMemberProfession] = useState(PROFESSION_OPTIONS[0]);
  const [memberCity, setMemberCity] = useState('');
  const [formError, setFormError] = useState('');

  const teamCode = partner?.teamCode || 'TL-ARJUN-884';
  const inviteUrl = `https://partner.primescore.in/register?ref=${teamCode}`;

  // Metrics Calculations
  const totalOnboarded = teamMembers.length;
  const totalOverrideEarned = teamMembers.reduce((acc, m) => acc + m.overridePointsEarned, 0);
  const totalCasesByTeam = teamMembers.reduce((acc, m) => acc + m.casesCount, 0);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(inviteUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(teamCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleOnboardSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!memberName || !memberEmail || !memberPhone || !memberCity) {
      setFormError('Please fill in all required member fields.');
      return;
    }

    onboardTeamMember({
      name: memberName,
      email: memberEmail,
      phone: memberPhone,
      profession: memberProfession,
      city: memberCity,
      status: 'kyc_approved',
    });

    // Reset Form & Close
    setMemberName('');
    setMemberEmail('');
    setMemberPhone('');
    setMemberCity('');
    setFormError('');
    setIsModalOpen(false);
  };

  const [selectedMember, setSelectedMember] = useState<typeof teamMembers[0] | null>(null);

  return (
    <div className="space-y-8 animate-fade-up font-body">
      {/* 1. Page Header & Primary Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/80 pb-5">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <UsersThree size={26} className="text-[#1B2A72]" weight="fill" />
            <h1 className="font-display text-2xl sm:text-3xl font-bold text-slate-900">
              Team Onboarding & Override Hub
            </h1>
            <span className="px-2.5 py-0.5 bg-[#1B2A72] text-white font-mono-num text-[10px] font-bold uppercase rounded-full">
              10% Cut Active
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-500 font-medium">
            Onboard new agents & advisors under your team. Earn an automatic 10% override cut on all referral points generated by your roster.
          </p>
        </div>

        <Button
          onClick={() => setIsModalOpen(true)}
          className="bg-[#1B2A72] hover:bg-[#0F1A4E] text-white font-bold px-4 py-2.5 rounded-xl inline-flex flex-row items-center justify-center gap-2 shrink-0 shadow-sm transition-all whitespace-nowrap text-xs"
        >
          <UserPlus size={16} weight="bold" className="shrink-0" />
          <span>Onboard New Team Member</span>
        </Button>
      </div>

      {/* 2. Team Metrics Stats Rail */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        <Card variant="elevated" className="p-6 rounded-2xl border border-slate-200/80 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold tracking-wider text-slate-400 font-mono-num">
              Total Onboarded Members
            </span>
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-[#1B2A72] flex items-center justify-center font-bold">
              <UsersThree size={22} weight="fill" />
            </div>
          </div>
          <p className="font-mono-num font-extrabold text-3xl text-slate-900 mt-3">
            {totalOnboarded}
          </p>
          <span className="text-xs text-slate-500 font-medium block mt-1">
            Active team advisors onboarded
          </span>
        </Card>

        <Card variant="elevated" className="p-6 rounded-2xl border border-slate-200/80 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold tracking-wider text-slate-400 font-mono-num">
              10% Override Revenue Cut
            </span>
            <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center font-bold">
              <Coins size={22} weight="fill" />
            </div>
          </div>
          <div className="flex items-baseline gap-2 mt-3">
            <p className="font-mono-num font-extrabold text-3xl text-[#1B2A72]">
              +{totalOverrideEarned.toLocaleString()}
            </p>
            <span className="font-display font-bold text-sm text-amber-500">Pts</span>
          </div>
          <span className="text-xs text-slate-500 font-medium block mt-1">
            Passive points earned from team cases
          </span>
        </Card>

        <Card variant="elevated" className="p-6 rounded-2xl border border-slate-200/80 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold tracking-wider text-slate-400 font-mono-num">
              Team Resolved Cases
            </span>
            <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold">
              <Lightning size={22} weight="fill" />
            </div>
          </div>
          <p className="font-mono-num font-extrabold text-3xl text-slate-900 mt-3">
            {totalCasesByTeam}
          </p>
          <span className="text-xs text-slate-500 font-medium block mt-1">
            Completed credit client cases by roster
          </span>
        </Card>
      </div>

      {/* 3. Team Leader Invite Code Bar (Clean High-Contrast White Card) */}
      <Card variant="elevated" className="p-6 rounded-2xl bg-white border border-slate-200/80 space-y-4 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center font-bold">
                <Sparkle size={16} weight="fill" />
              </div>
              <h3 className="font-display font-bold text-base text-slate-900">Your Team Leader Invite Code</h3>
            </div>
            <p className="text-xs text-slate-500 font-medium">
              Share your team invite link or code. Any new partner who registers with your code is automatically added to your team.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <div className="px-4 py-2 bg-amber-50 border border-amber-200/80 rounded-xl font-mono-num font-extrabold text-[#1B2A72] text-sm tracking-wider shadow-xs">
              {teamCode}
            </div>
            <Button
              onClick={handleCopyCode}
              variant="outline"
              className="bg-slate-50 hover:bg-slate-100 text-slate-700 border-slate-200 px-3.5 py-2 text-xs font-bold rounded-xl"
            >
              {copiedCode ? <CheckCircle size={16} className="text-emerald-600" /> : <Copy size={16} />}
              <span>{copiedCode ? 'Copied' : 'Copy Code'}</span>
            </Button>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row items-center gap-3 pt-3 border-t border-slate-100">
          <input
            type="text"
            readOnly
            value={inviteUrl}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 font-mono-num font-semibold focus:outline-none"
          />
          <Button
            onClick={handleCopyLink}
            className="w-full sm:w-auto bg-[#1B2A72] hover:bg-[#0F1A4E] text-white font-bold px-5 py-2.5 text-xs rounded-xl flex items-center justify-center gap-2 shadow-xs shrink-0"
          >
            {copiedLink ? <CheckCircle size={16} className="text-emerald-400" /> : <ShareNetwork size={16} />}
            <span>{copiedLink ? 'Link Copied!' : 'Copy Shareable Link'}</span>
          </Button>
        </div>
      </Card>

      {/* 4. Onboarded Members Roster Table */}
      <Card variant="elevated" className="p-6 rounded-2xl space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
          <div>
            <h3 className="font-display font-bold text-lg text-slate-900">
              Onboarded Team Members Roster ({totalOnboarded})
            </h3>
            <p className="text-xs text-slate-500 font-medium">
              Click any team member row below to view full contact details, KYC verification status, and override earnings history.
            </p>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-200/80 text-[11px] font-bold uppercase tracking-wider text-slate-400 font-mono-num bg-slate-50/50">
                <th className="py-3 px-4">Member Name</th>
                <th className="py-3 px-4">Profession</th>
                <th className="py-3 px-4">City</th>
                <th className="py-3 px-4">KYC Status</th>
                <th className="py-3 px-4 text-center">Cases</th>
                <th className="py-3 px-4 text-right">Member Earned</th>
                <th className="py-3 px-4 text-right">Your 10% Cut</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-xs font-medium text-slate-700">
              {teamMembers.map((m) => (
                <tr
                  key={m.id}
                  onClick={() => router.push(`/team/${m.id}`)}
                  className="hover:bg-slate-50/90 cursor-pointer transition-colors group"
                >
                  <td className="py-3.5 px-4">
                    <div>
                      <span className="font-bold text-slate-900 group-hover:text-[#1B2A72] transition-colors block">{m.name}</span>
                      <span className="text-[11px] text-slate-400 font-mono-num">{m.email}</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-4 font-semibold text-slate-800">{m.profession}</td>
                  <td className="py-3.5 px-4 text-slate-600">{m.city}</td>
                  <td className="py-3.5 px-4">
                    <span className="px-2.5 py-0.5 bg-emerald-50 text-emerald-700 border border-emerald-200 font-mono-num text-[10px] font-bold rounded-full uppercase">
                      KYC Approved
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-center font-mono-num font-bold text-slate-900">{m.casesCount}</td>
                  <td className="py-3.5 px-4 text-right font-mono-num font-bold text-slate-800">
                    {m.totalMemberPoints.toLocaleString()} Pts
                  </td>
                  <td className="py-3.5 px-4 text-right font-mono-num font-bold text-[#1B2A72] bg-indigo-50/40">
                    +{m.overridePointsEarned.toLocaleString()} Pts
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* 5. Modal: Directly Onboard New Team Member */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/65 animate-fade-in">
          <Card variant="elevated" className="max-w-md w-full p-6 sm:p-8 space-y-6 rounded-2xl bg-white relative">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div>
                <h3 className="font-display font-bold text-xl text-slate-900">Onboard Team Member</h3>
                <p className="text-xs text-slate-500 font-medium mt-0.5">
                  Directly register a new agent/advisor to your team roster.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 font-bold p-1 text-lg"
              >
                ✕
              </button>
            </div>

            {formError && (
              <div className="p-3 bg-red-50 border border-red-200 text-red-700 text-xs font-semibold rounded-xl">
                {formError}
              </div>
            )}

            <form onSubmit={handleOnboardSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1">
                  Member Full Name *
                </label>
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Sanjay Sharma"
                    value={memberName}
                    onChange={(e) => setMemberName(e.target.value)}
                    className="w-full px-3.5 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none focus:border-[#1B2A72] text-slate-900 transition-all font-medium"
                  />
                  <User size={18} className="absolute right-3.5 top-3 text-slate-400" />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1">
                  Email Address *
                </label>
                <div className="relative">
                  <input
                    type="email"
                    placeholder="sanjay@example.com"
                    value={memberEmail}
                    onChange={(e) => setMemberEmail(e.target.value)}
                    className="w-full px-3.5 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none focus:border-[#1B2A72] text-slate-900 transition-all font-medium"
                  />
                  <Envelope size={18} className="absolute right-3.5 top-3 text-slate-400" />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1">
                  Mobile Number *
                </label>
                <div className="relative">
                  <input
                    type="tel"
                    placeholder="9876543210"
                    value={memberPhone}
                    onChange={(e) => setMemberPhone(e.target.value)}
                    className="w-full px-3.5 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none focus:border-[#1B2A72] text-slate-900 font-mono-num transition-all"
                  />
                  <Phone size={18} className="absolute right-3.5 top-3 text-slate-400" />
                </div>
              </div>

              <CustomSelect
                label="Primary Profession Category *"
                options={PROFESSION_OPTIONS}
                value={memberProfession}
                onChange={(val) => setMemberProfession(val)}
                placeholder="Select profession..."
              />

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1">
                  City / Location *
                </label>
                <div className="relative">
                  <input
                    type="text"
                    placeholder="Mumbai, Pune, etc."
                    value={memberCity}
                    onChange={(e) => setMemberCity(e.target.value)}
                    className="w-full px-3.5 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none focus:border-[#1B2A72] text-slate-900 transition-all font-medium"
                  />
                  <MapPin size={18} className="absolute right-3.5 top-3 text-slate-400" />
                </div>
              </div>

              <div className="pt-2 flex items-center justify-end gap-3">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2.5 text-xs font-bold rounded-xl"
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  className="bg-[#1B2A72] hover:bg-[#0F1A4E] text-white font-bold px-5 py-2.5 text-xs rounded-xl shadow-md"
                >
                  Confirm & Onboard Member
                </Button>
              </div>
            </form>
          </Card>
        </div>
      )}
    </div>
  );
}
